[package]
name         = "rdk-clearing"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }

[dependencies]
rdk-clob    = { workspace = true }
rdk-funding = { workspace = true }
serde          = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
