[package]
name         = "rdk-clob"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }

[dependencies]
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
arc-swap = { workspace = true }

[lints]
workspace = true

[[bench]]
name    = "read_contention"
harness = false
